# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *" # repeat every day

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        
  Test:
    needs: Linting
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}   
    strategy:
      matrix:
        os: [ubuntu-latest]
        postgis: [false]
        dev: [false]
        env:
          - ci/envs/38-latest-conda-forge.yaml
        include:
          - env: ci/envs/38-latest-conda-forge.yaml
            os: macos-latest
            postgis: false
            dev: false
          - env: ci/envs/38-latest-conda-forge.yaml
            os: windows-latest
            postgis: false
            dev: false
          - env: ci/envs/38-latest-conda-forge.yaml
            os: ubuntu-latest
            postgis: false
            dev: false
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        
    - name: Install Env
      shell: bash
      run: conda env create -f ${{ matrix.env }}
        
    - name: Test with pytest
      run: |
        pytest --cov-report xml trackintel/
